### ISSUE TITLE
下拉刷新的时候，向下滚动，再回到顶部，刷新状态就没了

### ISSUE THREAD

**Issue by CodeCatLYR** [dinuscxj/RecyclerRefreshLayout#10]
RecyclerRefreshLayout 下拉刷新，然后向下滚动， 再回到顶部， 刷新的状态和动画就不见了

**Comment by dinuscxj** [comment]
@CodeCatLYR 那是刷新结束了啊， 逻辑本来就该是这样的

**Comment by CodeCatLYR** [comment]
嗯嗯，我说的不是刷新结束的情况，是还在请求，然后向下滑动，看不见刷新头部之后，再向上滑动到顶部，只能滑动到RecyclerView 的最顶部，不会出现刷新中的控件....

**Comment by dinuscxj** [comment]
@CodeCatLYR     你的这个问题    compile 'com.dinuscxj:recyclerrefreshlayout:2.0.2'应该已经解决啦
