### ISSUE TITLE
如何使用官方SwipeRefreshLayout的刷新效果呢？

### ISSUE THREAD

**Issue by loganguo** [dinuscxj/RecyclerRefreshLayout#12]
刷新圆圈的效果想改成官方效果https://material.google.com/patterns/swipe-to-refresh.html#

**Comment by dinuscxj** [comment]
@loganguo 你可以参考android.support.v4.widget.MaterialProgressDrawable

**Comment by loganguo** [comment]
试着改了下，没有改成功，遇到的问题是`public void setRefreshView(View refreshView, ViewGroup.LayoutParams layoutParams)`需要的是一个view，而`MaterialProgressDrawable`是一个drawable。

我试着新建了一个自定义的view类，它实现`IRefreshStatus`接口，参照`android.support.v4.widget.MaterialProgressDrawable`和`android.support.v4.widget.SwipeRefreshLayout`作法，但是把MaterialProgressDrawable分别设置到接口`IRefreshStatus`中的那5个方法中去的时候，进行不下去了，没搞明白到底如何修改。@dinuscxj能否大致说一下处理方法呢？
