### ISSUE TITLE
为什么在我写的demo里。会出现这种情况

### ISSUE THREAD

**Issue by YangShaoXiong** [dinuscxj/RecyclerRefreshLayout#19]
设置自动刷新setRefreshing(true)，不回调onRefresh方法，还有就是RefreshView不设置pinned紧贴底部，设置pinned紧贴顶部，然而在你给出的demo里，没有我说的这种情况，我也仔细看了你给出的demo。发现也没有什么不同之处，唯一不同就是adapter我用了这个库[https://github.com/CymChad/BaseRecyclerViewAdapterHelper]([https://github.com/CymChad/BaseRecyclerViewAdapterHelper),![](http://i2.buimg.com/567571/5400a0a5f30c63ea.png)
麻烦在百忙之中，看看能否帮我只个招。提前谢谢了。

**Comment by dinuscxj** [comment]
你可以通过 RecyclerRefreshLayout.setRefreshTargetOffset(float)设置一下位置

**Comment by YangShaoXiong** [comment]
还有个问题就是，我在onCreate方法里直接调用setRefreshing(true)的方法，也就是我想让已进入该页面就去自动执行下拉刷新效果。但是它不响应onRefresh方法了

**Comment by dinuscxj** [comment]
嗯嗯 不响应onRefresh是正确的行为， android自带的SwipeRefreshLayout就是这样的， 一般的封装行为都是调用setRefreshing(true)然后调用网络请求

**Comment by YangShaoXiong** [comment]
OK。原来这样啊。那么问题来了，就是在下拉刷新的时候，会出现屏幕上所有的控件会失去焦点，就是在下拉刷新的时候，不能再滑动列表，只能等它下拉刷新完成。

**Comment by dinuscxj** [comment]
@YangShaoXiong 你使用的是最新版本吗？
