### ISSUE TITLE
The design of tips is too complex  to understand

### ISSUE THREAD

**Issue by yummyChina** [dinuscxj/RecyclerRefreshLayout#4]
the show and hide of the tipview is so  complicated, every action of tip take serversal inovke.I think it should be simplified. Maybe remove the tipview will reduce the use the of system's resource when it should be hidden,but  the  the cost of let it visible or invisible is as same as add view or remove view
frequently,I think.

**Comment by dinuscxj** [comment]
You can see the tips view as a tools. maybe you need custom it for yourself. remove the tips view will reduce the use the of system's resource when it should be hidden, but in fact,  it will be not useful for the current window when the RecyclerView or the ListView received the response from network.  As you know,  if the tips view is removed,  it will cost none for the current window.  thanks for you feedback.
