### ISSUE TITLE
上拉加载怎么用这个实现？

### ISSUE THREAD

**Issue by Lyon1994** [dinuscxj/RecyclerRefreshLayout#5]
示例中有动图介绍有这个功能，但是我不知道应该调用什么方法去实现

**Comment by dinuscxj** [comment]
@Lyon1994，这是demo里面添加的， 通过demo里面的HeaderViewRecyclerAdapter控制footerview实现的

**Comment by dinuscxj** [comment]
@Lyon1994 如果还有什么问题不理解可以加入我的开源答疑qq群: 342748245
