### ISSUE TITLE
TipsUtils do not support viewpager

### ISSUE THREAD

**Issue by 416679828** [dinuscxj/RecyclerRefreshLayout#7]
how to support viewpager use TipsUtils?

**Comment by 416679828** [comment]
When i use viewpager add Fragment, the Fragment do not show in my expected!  I used  TipsUtils.show ,but it did not work

**Comment by dinuscxj** [comment]
do you want to use the TipsUtils to control the show and the hide of the ViewPager?  I can sure it will work well, because my company has used the tipsUtils in any situations, maybe you are using the TipUtils in the wrong way.  if you want to learn more, you can join the **QQ group: 342748245**

**Comment by 416679828** [comment]
算了，不装逼了，还是用中文吧。我的意思是当我用viewpager add fragment时,fragment不会显示等待,错误这个tips布局,我是在framgnet的oncreateview里面就已经让他tips.show(),但是他并不会show(),显示是空白的布局，我只有把他hide tips才会显示fragment布局。

**Comment by 416679828** [comment]
viewpager是能替换,是当我addfragment之后,在fragment里面不会正常工作

**Comment by dinuscxj** [comment]
@416679828 显示的空白布局应该就是show的布局，你可以调试下，看看白色的布局是什么， 为什么子布局没有显示。我顺便也做一个demo试试

**Comment by dinuscxj** [comment]
其实你这样的场景在我公司的项目里面也有， 我怀疑是你的布局有问题

**Comment by dinuscxj** [comment]
@416679828 我这里测试的没有问题， 我怀疑你不包在viewpager中你的这个Fragment也有问题！

**Comment by dinuscxj** [comment]
@416679828 我已经将我写的demo推上来啦， 你可以重新git clone 一下！

**Comment by 416679828** [comment]
好的，谢谢
