### ISSUE TITLE
post主动刷新的效果有了

### ISSUE THREAD

**Issue by junchenChow** [dinuscxj/RecyclerRefreshLayout#9]
`refreshLayout.postDelayed(() -> refreshLayout.setRefreshing(false), 500);` 调用刷新完毕会多回弹一下

**Comment by junchenChow** [comment]
用真实数据的时候 还出现了一个问题 就是下拉刷新后 弹回去之后 又抖动了一下，意思就是刷新效果完成了之后它自己又弹了一下。 我看demo没有 不知道是不是我的使用姿势不对。
这个是简单初始化的代码 
`refreshLayout.setOnRefreshListener(this::beforeRefresh);
        ViewGroup.LayoutParams layoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        refreshLayout.setRefreshView(new RefreshHeaderView(getActivity()), layoutParams);
        refreshLayout.setDragDistanceConverter(new DragDistanceConverterEg());
        refreshLayout.post(() -> refreshLayout.setRefreshing(true));
        beforeRefresh();`

**Comment by junchenChow** [comment]
第一个问题 我的锅 确实不会进

**Comment by dinuscxj** [comment]
收到，你这个我在demo里面复现不了！在你手机是必现吗？

**Comment by junchenChow** [comment]
嗯 直接调用`refreshLayout.setRefreshing(false)` 就没有再回弹  但是delayed一下的话 弹回去了后 又上下弹了一下 具体不太清楚是啥原因 会不会是我自己的锅

**Comment by dinuscxj** [comment]
嗯嗯！我周末看下！ refreshLayout.setRefreshing(false)，但是这个函数设置fasle时 postdelayed场景确实罕见！ 这个函数设置为true的场景很常见

**Comment by junchenChow** [comment]
这个场景主要是不想让刷新效果很快的弹回去
让上面自定义的header动画稍微延迟个几百毫秒再回去 这样感觉就不会看起来很突兀 ～ ^_^

**Comment by BeginsDesign** [comment]
能上拉加载更多吗？

**Comment by dinuscxj** [comment]
@BeginsDesign demo里面是有的

**Comment by BeginsDesign** [comment]
@dinuscxj 下载下来试一下，谢谢你！
